name: dkv-credit-risk

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - matplotlib==3.10.9
      - joblib
      - mlflow==2.16.2
      - azureml-mlflow==1.60.0
      - ucimlrepo